# Generated by Django 2.2.3 on 2020-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searches', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='stations',
        ),
    ]
